### ISSUE TITLE
[question] No examples of using the CLI tool

### ISSUE THREAD

**Issue by HoneyBearCodes** [sleeyax/aternos-api#3]
There are example illustrating the programmatic approach, but for CLI, there are no clear instruction. When I tried to run CLI, it displayed me a help message with bunch of options I can provide to it for example proxy, server and session, etc. But I don't know how to use them or what they are. I mean am I supposed to enter the server address, I don't know what proxy and session are etc. I would be great if provided me a detailed explanation with some examples.

**Comment by sleeyax** [comment]
This library is meant for programmers, see https://github.com/sleeyax/aternos-discord-bot if you need more examples regarding configuration, it uses this library. Also see https://github.com/sleeyax/aternos-discord-bot/discussions/9#discussioncomment-2540110 for a video tutorial. The parameters for the discord bot are similar to the provided CLI of this repo.

**Comment by HoneyBearCodes** [comment]
Great!! Thank!

**Comment by sleeyax** [comment]
I think you have a point this repo can use some more documentation though. But on the other hand, developers who use this library most likely already know what these parameters are.
